refactor: show changelog types using multi-line strings
equinor/template-fastapi-react pull request #196
Opened 2023-03-10 10:04 UTC by eoaksnes

## Why is this pull request needed?

* Easier to see how changelog-types are configured

## What does this pull request change?

* Single-line to multi-line configuration of changelog types

## Issues related to this change:

2023-03-10 13:42 UTC, jorgenengelsen approved these changes

2023-03-10 13:49 UTC, ingeridhellen requested changes
I don't think this will work. Can you test it first?

2023-09-29 10:47 UTC, sebastianvitterso commented
@eoaksnes Has this been tested now? This has been stale since March!

2025-01-14 07:52 UTC, sebastianvitterso commented
This PR is now 18 months old. It should be able to walk on its own by now. 
Will this get merged @eoaksnes ?

2025-02-24 10:58 UTC, closed without merging