Feature/use docusaurus
equinor/template-fastapi-react pull request #71
Opened 2022-09-20 07:58 UTC by ingeridhellen

## Why is this pull request needed?

It has been decided to switch from Doctave to Docusaurus, as the latter has more features and is easier to set up.

## What does this pull request change?

Moves current documentation from Doctave to Docusaurus

## Issues related to this change:

Closes #70

2022-09-21 08:48 UTC, sebastianvitterso commented
I want dark-mode to work by default (if you have dark mode in OS). 

Docusaurus docs: https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme:~:text=single%20color%20mode.-,respectPrefersColorScheme,-boolean

2022-09-21 08:52 UTC, sebastianvitterso commented on documentation/package.json
> +  "version": "0.0.0",
`0.0.0`? 😳

2022-09-21 08:54 UTC, sebastianvitterso approved these changes
Looks good!

2022-09-21 08:56 UTC, eoaksnes commented
To include plantUML files we can use https://github.com/webgears/remarkable-plantuml

2022-09-21 08:58 UTC, eoaksnes requested changes
Rename from Tutorial to Docs + use try to use https://github.com/webgears/remarkable-plantuml to show plantUML diagrams.

2022-09-21 08:58 UTC, eoaksnes commented on documentation/docusaurus.config.js
> +                  label: 'Tutorial',
Rename to Docs :)

2022-09-21 13:25 UTC, ingeridhellen commented
> 

Don't think it will work: https://github.com/webgears/remarkable-plantuml/issues/1. Besides, the repo seems forgotten, last commit was 4 years ago.

2022-09-21 13:25 UTC, sebastianvitterso approved these changes

2022-09-21 13:25 UTC, ingeridhellen commented
> To include plantUML files we can use https://github.com/webgears/remarkable-plantuml

Don't think it will work: https://github.com/webgears/remarkable-plantuml/issues/1. Besides, the repo seems forgotten, last commit was 4 years ago.

2022-09-21 14:10 UTC, sebastianvitterso approved these changes

2022-09-22 15:00 UTC, eoaksnes approved these changes
Nice work!

2022-09-23 06:00 UTC, merged